[package]
name = "noirstarter"
type = "bin"
authors = [""]
compiler_version = ">=0.19.0"

[dependencies]
ecrecover = { tag = "v0.19.0", git = "https://github.com/colinnielsen/ecrecover-noir.git" }
# ecrecover = {tag = "v0.16.1", git = "https://github.com/signorecello/ecrecover-noir.git"}